### ISSUE TITLE
Dataset not found: HAR

### ISSUE THREAD

**Issue by Ziy1-Tan** [emadeldeen24/AdaTime#3]
Hello! I'm trying to run the project, but I have a little trouble.
1. clone the project and put the folder HAR on `data`
```shell 
har # tree -L 2 .
.
├── algorithms
│   ├── algorithms.py
│   └── __pycache__
├── configs
│   ├── data_model_configs.py
│   ├── hparams.py
│   ├── __pycache__
│   └── sweep_params.py
├── data
│   ├── HAR -> /home/xxx/research/dataset/HAR
│   └── README.md
...

13 directories, 20 files
```
3. run
```shell
python main.py --experiment_description exp1  \ 
                --run_description run_1 \
                --da_method DANN \
                --backbone CNN \
                --num_runs 5 \
                --is_sweep False
```
3. report the error:
```python
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    trainer = cross_domain_trainer(args)
  File "/home/xxx/research/code/AdaTime/trainer.py", line 59, in __init__
    self.dataset_configs, self.hparams_class = self.get_configs()
  File "/home/xxx/research/code/AdaTime/trainer.py", line 203, in get_configs
    dataset_class = get_dataset_class(self.dataset)
  File "/home/xxx/research/code/AdaTime/configs/data_model_configs.py", line 4, in get_dataset_class
    raise NotImplementedError("Dataset not found: {}".format(dataset_name))
NotImplementedError: Dataset not found: HAR
```

**Comment by emadeldeen24** [comment]
We apologize for this issue. It is fixed now. Please check the [updated config file](https://github.com/emadeldeen24/AdaTime/blob/main/configs/data_model_configs.py).

Best.
